name: Jira

on:
  push:
    branches:
      - 'main'

jobs:
  jira:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find in commit messages
        uses: atlassian/gajira-find-issue-key@v3
        with:
          from: commits
      - name: Remove Jira ref from commit
        uses: actions/github-script@v6
        id: commit
        with:
          script: |
            core.setOutput("message", "${{ github.event.head_commit.message }}".replace(/\S+-\d+/, ''));
      - name: Comment on issue
        uses: atlassian/gajira-comment@v3
        with:
          comment: '${{ github.event.pusher.name }} pushed to repository ${{ github.event.repository.full_name }} with commit message: ${{ steps.commit.outputs.message }}'
